### ISSUE TITLE
BLE Privacy mode

### ISSUE THREAD

**Issue by gronkdaslayer** [microsoft/BluetoothLEExplorer#14]
While this is not an actual issue with the BLE Explorer code, I would like to know if there is an API that would allow us to turn off the BLE Privacy mode. The problem is that, when you write a GATT service, the BT address will change periodically (or even when you wake up from sleep) and because of that, the notification subscribers will no longer receive notifications.

It's possible to get the static address and set it as static on Linux and I would assume that the Windows BT stack can do this as well (since it's in the BT 4.0 specs) but there's no (user mode) API for it. Even if it is possible to accomplish this by sending an IOCTL to the driver, that'd be great but I don't know what the IOCTL would be.

**Comment by Sinorm** [comment]
It shouldn't be necessary to disable LE privacy for notifications to work, and we don't allow applications to disable privacy since it is a security issue.

1.	A random address will not change while the peripheral is connected and we will continue to receive notifications.
2.	If a device is disconnected, potentially due to a suspend/resume, then the address would change potentially.  This results in two potential conditions:
a.	If the device is paired, it must provide an IRK for us as part of the SMP ceremony for us to resolve the random address.  If this is not done by the device, then there is no way to resolve it (device issue).  If the device correctly provides an IRK all of this will happen automatically. (Note: Some older versions of Windows had an issue with this, try the latest builds through the Windows Insider program and this should work as expected).
b.	If the device is not paired, or if the device failed to provide us with an IRK, then the device must be rediscovered via the advertisement payload and a new GattDeviceService/BluetoothLEDevice object constructed for that device and the CCCD must be resubscribed.  At this point the device must be treated as unpaired/loosely coupled.

I hope that helps.
